name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Extract version from Cargo.toml'
        id: cargo_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: 'Build and Push Docker Image with version tag'
        run: |
          docker build . --tag ghcr.io/vss96/t3elric-engine:${{ env.version }} --tag ghcr.io/vss96/t3elric-engine:latest
          docker push ghcr.io/vss96/t3elric-engine:${{ env.version }}
          docker push ghcr.io/vss96/t3elric-engine:latest